<?php 

return [
    [
        'user_id'=>1,
        "name" => "Ristorante Da Mario",
        "vat_number" => "12345678910",
        "note" => "Piatti vegani e gluten free",
        "thumb" => "RistoranteDaMario.jpg",
        "street_name" => "Viale Giacomo Porelli",
        "street_number" => "12",
        "zip_code" => "40562",
    ],
    [
        'user_id'=>2,
        "name" => "Lago",
        "vat_number" => "24529568431",
        "note" => "Cucina italiana tradizionale di pesce",
        "thumb" => "lago.jpg",
        "street_name" => "Viale Galli",
        "street_number" => "52",
        "zip_code" => "34522",
    ],
    [
        'user_id'=>3,
        "name" => "Memento Burger",
        "vat_number" => "01229568431",
        "note" => "Ordine minimo 15 € ",
        "thumb" => "MementoBurger.webp",
        "street_name" => "Via Baldo Degli Ubaldi",
        "street_number" => "92",
        "zip_code" => "00167",
    ],
    [
        'user_id'=>4,
        "name" => "Poke House - Roma",
        "vat_number" => "00154667898",
        "note" => "La tua scelta salutare",
        "thumb" => "PokeHouseRoma.webp",
        "street_name" => "Via del Gambero",
        "street_number" => "36",
        "zip_code" => "00187",
    ],
    [
        'user_id'=>5,
        "name" => "Moko Sushi",
        "vat_number" => "22559876511",
        "note" => "Consegna Gratuita",
        "thumb" => "MokoSushi.webp",
        "street_name" => "Via Piacenza",
        "street_number" => "1",
        "zip_code" => "20135",
    ],
    [
        'user_id'=>6,
        "name" => "Il Principe Pizzeria Rosticceria",
        "vat_number" => "37654929299",
        "note" => "",
        "thumb" => "IlPrincipePizzeriaRosticceria.jpg",
        "street_name" => "Via Piacenza",
        "street_number" => "1",
        "zip_code" => "20135",
    ],
    [
        'user_id'=>7,
        "name" => "Cipiace",
        "vat_number" => "55692987262",
        "note" => "Il ristorante accetta solo carta di credito o PayPal",
        "thumb" => "Cipiace.webp",
        "street_name" => "Corso di Vittoria",
        "street_number" => "21",
        "zip_code" => "20122",
    ],
    [
        'user_id'=>8,
        "name" => "Chicken Drip",
        "vat_number" => "55692987262",
        "note" => "",
        "thumb" => "ChickenDrip.webp",
        "street_name" => "Via California",
        "street_number" => "15",
        "zip_code" => "20144",
    ],
    [
        'user_id'=>9,
        "name" => "Old Wild West",
        "vat_number" => "55696547262",
        "note" => "Ordine minimo 15 € ",
        "thumb" => "OldWildWest.webp",
        "street_name" => "Piazza del Duomo",
        "street_number" => "25",
        "zip_code" => "40020",
    ],
    [
        'user_id'=>10,
        "name" => "McDonald's",
        "vat_number" => "12359637267",
        "note" => "Il ristorante accetta i buoni pasto.",
        "thumb" => "McDonalds.webp",
        "street_name" => "Galleria Ciro Fontana",
        "street_number" => "3",
        "zip_code" => "40023",
    ],
    [
        'user_id'=>11,
        "name" => "Fusho",
        "vat_number" => "16789637267",
        "note" => "Il ristorante accetta i buoni pasto.",
        "thumb" => "Fusho.webp",
        "street_name" => "Via Paolo Sarpi ",
        "street_number" => "50",
        "zip_code" => "41023",
    ],
    [
        'user_id'=>12,
        "name" => "Ravioleria Sarpi",
        "vat_number" => "16789637852",
        "note" => " Il ristorante accetta solo pagamenti online tramite carta di credito o PayPal ",
        "thumb" => "RavioleriaSarpi.webp",
        "street_name" => "Via Paolo Sarpi ",
        "street_number" => "50",
        "zip_code" => "41023",
    ],
    [
        'user_id'=>13,
        "name" => "Eat Mang Isidro Chicken",
        "vat_number" => "46836637852",
        "note" => " Il ristorante accetta solo pagamenti online tramite carta di credito o PayPal ",
        "thumb" => "EatMangIsidroChicken.jpg",
        "street_name" => "Corso di Porta Romana",
        "street_number" => "94",
        "zip_code" => "20122",
    ],
    [
        'user_id'=>14,
        "name" => "Tyche Greek Pita Gyros",
        "vat_number" => "66996635588",
        "note" => " Il ristorante accetta solo pagamenti online tramite carta di credito o PayPal ",
        "thumb" => "TycheGreekPitaGyros.jpg",
        "street_name" => "Corso di Porta Ticinese",
        "street_number" => "40",
        "zip_code" => "20123",
    ],
    [
        'user_id'=>15,
        "name" => "KFC",
        "vat_number" => "77556635588",
        "note" => "Il ristorante accetta i buoni pasto.",
        "thumb" => "KFC.webp",
        "street_name" => "Piazza Duca d'Aosta",
        "street_number" => "1",
        "zip_code" => "20124",
    ],
    [
        'user_id'=>16,
        "name" => "Punto Pizza",
        "vat_number" => "99776635588",
        "note" => " offerte: ogni 2 pizze, una bibita in omaggio; ogni spesa da 20 euro, una bibita in bottiglia grande in omaggio. Specifica la scelta nelle note. Offerte non cumulabili con altre offerte in corso.",
        "thumb" => "PuntoPizza.webp",
        "street_name" => "Via Edolo",
        "street_number" => "41",
        "zip_code" => "20125",
    ],
    [
        'user_id'=>17,
        "name" => "Noyi Chef Sushi",
        "vat_number" => "88666635588",
        "note" => " ",
        "thumb" => "NoyiChefSushi.webp",
        "street_name" => "Via Pellegrino Rossi",
        "street_number" => "51",
        "zip_code" => "20125",
    ],
    [
        'user_id'=>18,
        "name" => "Al Noor 2 Rosticceria Indiana",
        "vat_number" => "11006635588",
        "note" => " ",
        "thumb" => "AlNoor2RosticceriaIndiana.webp",
        "street_name" => "Via Edoardo Bassini",
        "street_number" => "47",
        "zip_code" => "20133",
    ],
    [
        'user_id'=>19,
        "name" => "Isola della Pizza",
        "vat_number" => "22554435588",
        "note" => " Il ristorante non accetta i buoni pasto",
        "thumb" => "IsoladellaPizza.jpg",
        "street_name" => "Via Garigliano",
        "street_number" => "12",
        "zip_code" => "20159",
    ],
    [
        'user_id'=>20,
        "name" => "Pronto Pizza",
        "vat_number" => "23614435588",
        "note" => " Ricevi gratuitamente: Bibita 1,5L - Coca Cola, se spendi 25 €",
        "thumb" => "ProntoPizza.webp",
        "street_name" => "Via Bassini",
        "street_number" => "24",
        "zip_code" => "20149",
    ],
    [
        'user_id'=>21,
        "name" => "Pizzeria Folomina",
        "vat_number" => "12344435588",
        "note" => " Il ristorante accetta i seguenti buoni pasto: CityTime, Day, Passlunch, Pellegrini, Ristomat, Sodexo, Ticket Restaurant.",
        "thumb" => "PizzeriaFolmina.jpg",
        "street_name" => "Via Lorenzo Bartolini",
        "street_number" => "51",
        "zip_code" => "20155",
    ],
    [
        'user_id'=>22,
        "name" => "Indian Vegetarian Food",
        "vat_number" => "15422435588",
        "note" => " Il ristorante non accetta buoni pasto.",
        "thumb" => "IndianVegetarianFood.jpg",
        "street_name" => "Via Giuseppe Ripamont",
        "street_number" => "15",
        "zip_code" => "20136",
    ],
    [
        'user_id'=>23,
        "name" => "Jollibee",
        "vat_number" => "88554435588",
        "note" => "Il ristorante accetta i buoni pasto.",
        "thumb" => "Jollibee.jpg",
        "street_name" => "Piazza Armando Diaz",
        "street_number" => "7",
        "zip_code" => "20123",
    ],
    [
        'user_id'=>24,
        "name" => "Trattoria La Muraglia",
        "vat_number" => "99664435588",
        "note" => "  Il ristorante accetta solo pagamenti online tramite carta di credito o PayPal €",
        "thumb" => "TrattoriaLaMuraglia.jpg",
        "street_name" => "Viale Toscana ",
        "street_number" => "19",
        "zip_code" => "20141",
    ],
    [
        'user_id'=>25,
        "name" => "My Heart Burger Normale e Senza Glutine",
        "vat_number" => "39654435588",
        "note" => "Il ristorante accetta i buoni pasto.",
        "thumb" => "MyHeartBurgerNormaleSenzaGlutine.webp",
        "street_name" => "Via Amatore Sciesa ",
        "street_number" => "1",
        "zip_code" => "20135",
    ],
    [
        'user_id'=>26,
        "name" => "Al Noor Rosticceria Indiana - Imbriani",
        "vat_number" => "88694435588",
        "note" => "Il ristorante accetta i buoni pasto.",
        "thumb" => "AlNoorRosticceriaIndiana-Imbriani.webp",
        "street_name" => "Via degli Imbriani",
        "street_number" => "6",
        "zip_code" => "20158",
    ],
    [
        'user_id'=>27,
        "name" => "Guzzo - Burger Ignoranti",
        "vat_number" => "36994438861",
        "note" => "Il ristorante accetta solo pagamenti online tramite carta di credito o PayPal",
        "thumb" => "Guzzo-BurgerIgnoranti.webp",
        "street_name" => "Via Ruggero Boscovich",
        "street_number" => "22",
        "zip_code" => "20124",
    ],
    [
        'user_id'=>28,
        "name" => "Wen Cheng",
        "vat_number" => "36994443688",
        "note" => "Il ristorante accetta solo pagamenti online tramite carta di credito o PayPal",
        "thumb" => "WenCheng.webp",
        "street_name" => "Via Giordano Bruno",
        "street_number" => "20",
        "zip_code" => "20124",
    ],
    [
        'user_id'=>29,
        "name" => "Luini",
        "vat_number" => "97544443688",
        "note" => "Il ristorante accetta solo pagamenti online tramite carta di credito o PayPal",
        "thumb" => "Luini.webp",
        "street_name" => "Via Santa Radegonda",
        "street_number" => "2160",
        "zip_code" => "201",
    ],
    [
        'user_id'=>30,
        "name" => "Insalateria - Casati",
        "vat_number" => "36498443688",
        "note" => "Ristorante con carta fedeltà",
        "thumb" => "InsalateriaCasati.webp",
        "street_name" => "Via Felice Casati",
        "street_number" => "39",
        "zip_code" => "20124",
    ],
    [
        'user_id'=>31,
        "name" => "Speedy Pita",
        "vat_number" => "9658443688",
        "note" => "Il ristorante non accetta i buoni pasto.",
        "thumb" => "SpeedyPita.webp",
        "street_name" => "Via Consalvo Carelli",
        "street_number" => "26",
        "zip_code" => "80129",
    ],
    [
        'user_id'=>32,
        "name" => "O'Tacos - Fuorigrotta",
        "vat_number" => "3542443688",
        "note" => "Il ristorante accetta solo pagamenti online tramite carta di credito o PayPal",
        "thumb" => "OTacos-Fuorigrotta.webp",
        "street_name" => "Via Vicinale Cupa Cintia",
        "street_number" => "249/251",
        "zip_code" => "80126",
    ],
    [
        'user_id'=>33,
        "name" => "Messico e Nuvole",
        "vat_number" => "3542445841",
        "note" => "Il ristorante non accetta i buoni pasto.",
        "thumb" => "MessicoeNuvole.jpg",
        "street_name" => "Via XX Settembre ",
        "street_number" => "31",
        "zip_code" => "19038",
    ],
    [
        'user_id'=>34,
        "name" => "El Salvador Ristorante Messicano",
        "vat_number" => "6542445841",
        "note" => "Il ristorante accetta solo pagamenti online tramite carta di credito o PayPal",
        "thumb" => "ElSalvador.webp",
        "street_name" => "Via Roma ",
        "street_number" => "178",
        "zip_code" => "84121",
    ],
    [
        'user_id'=>35,
        "name" => "El Moccolo Comida Messicana",
        "vat_number" => "6542448862",
        "note" => "Il ristorante accetta solo pagamenti online tramite carta di credito o PayPal",
        "thumb" => "ElMoccolo.jpg",
        "street_name" => "Via Giovanni Bausan",
        "street_number" => "5",
        "zip_code" => "80121",
    ],
    [
        'user_id'=>36,
        "name" => "Billy Tacos",
        "vat_number" => "4587448862",
        "note" => "Il ristorante accetta solo pagamenti online tramite carta di credito o PayPal",
        "thumb" => "BillyTacos.webp",
        "street_name" => "Via Serioletta",
        "street_number" => "4",
        "zip_code" => "46040",
    ],
    [
        'user_id'=>37,
        "name" => "Opà Opà - La Grecia a Milano",
        "vat_number" => "5463448862",
        "note" => "Il ristorante accetta solo pagamenti online tramite carta di credito o PayPal",
        "thumb" => "OpaOpa.webp",
        "street_name" => "Via Luigi Porro Lambertenghi",
        "street_number" => "19",
        "zip_code" => "20159",
    ],
    [
        'user_id'=>38,
        "name" => "Wannas Cucina Greca - Pita & Pizza",
        "vat_number" => "8806448862",
        "note" => "Il ristorante non accetta i buoni pasto",
        "thumb" => "WannasCucinaGreca.jpg",
        "street_name" => "Via Pietro Maroncelli",
        "street_number" => "19",
        "zip_code" => "20154",
    ],
    [
        'user_id'=>39,
        "name" => "Burrito Bar - Casati",
        "vat_number" => "8806449058",
        "note" => "Il ristorante non accetta i buoni pasto",
        "thumb" => "BurritoBar-Casati.webp",
        "street_name" => "Via Felice Casati",
        "street_number" => "39",
        "zip_code" => "20124",
    ],
    [
        'user_id'=>40,
        "name" => "Natural Break",
        "vat_number" => "0645449058",
        "note" => "Il ristorante non accetta i buoni pasto",
        "thumb" => "NaturalBreak.webp",
        "street_name" => "Via Giovanni Boccaccio",
        "street_number" => "15",
        "zip_code" => "20123",
    ],
    [
        'user_id'=>41,
        "name" => "Pizza Senza Glutine - My Heart",
        "vat_number" => "0039449058",
        "note" => "Il ristorante non accetta i buoni pasto",
        "thumb" => "PizzaSenzaGlutineMyHeart.jpg",
        "street_name" => "Via Amatore Sciesa",
        "street_number" => "1",
        "zip_code" => "20135",
    ],
    [
        'user_id'=>42,
        "name" => "Ciapa El Taco",
        "vat_number" => "6005449058",
        "note" => "Il ristorante non accetta i buoni pasto",
        "thumb" => "CiapaElTaco.jpg",
        "street_name" => "Via Francesco Brioschi",
        "street_number" => "16",
        "zip_code" => "20136",
    ],
    [
        'user_id'=>43,
        "name" => "Koshitsu",
        "vat_number" => "8500449058",
        "note" => "Il ristorante non accetta i buoni pasto",
        "thumb" => "Koshitsu.jpg",
        "street_name" => "Via Lazzaro Palazzi",
        "street_number" => "24",
        "zip_code" => "20124",
    ],
    [
        'user_id'=>44,
        "name" => "Ristorante Tara",
        "vat_number" => "9604449058",
        "note" => "Il ristorante accetta solo pagamenti online tramite carta di credito o PayPal",
        "thumb" => "RistoranteTara.jpg",
        "street_name" => "Via Domenico Cirillo",
        "street_number" => "16",
        "zip_code" => "20154",
    ],
    [
        'user_id'=>45,
        "name" => "Ristorante Tara",
        "vat_number" => "7614449058",
        "note" => "Il ristorante accetta solo pagamenti online tramite carta di credito o PayPal",
        "thumb" => "TheDhaba.webp",
        "street_name" => "Via Panfilo Castaldi",
        "street_number" => "22",
        "zip_code" => "20124",
    ],
    [
        'user_id'=>46,
        "name" => "Zaika Indiano - Imbriani",
        "vat_number" => "7463449058",
        "note" => "Il ristorante accetta solo pagamenti online tramite carta di credito o PayPal",
        "thumb" => "ZaikaIndiano-Imbriani.webp",
        "street_name" => "Via degli Imbriani",
        "street_number" => "6",
        "zip_code" => "20158",
    ],
    [
        'user_id'=>47,
        "name" => "Pizza Bufalina",
        "vat_number" => "8807449058",
        "note" => "Il ristorante accetta solo pagamenti online tramite carta di credito o PayPal",
        "thumb" => "PizzaBufalina.webp",
        "street_name" => "Via Bartolomeo Eustachi",
        "street_number" => "6",
        "zip_code" => "20129",
    ],
    [
        'user_id'=>48,
        "name" => "Raj Ristorante Indiano",
        "vat_number" => "3707449058",
        "note" => "Il ristorante accetta solo pagamenti online tramite carta di credito o PayPal",
        "thumb" => "RajRistoranteIndiano.webp",
        "street_name" => "Via Lodovico Il Moro",
        "street_number" => "36",
        "zip_code" => "20143",
    ],
    [
        'user_id'=>49,
        "name" => "PanBolla",
        "vat_number" => "0209449058",
        "note" => "Il ristorante accetta solo pagamenti online tramite carta di credito o PayPal",
        "thumb" => "PanBolla.jpg",
        "street_name" => "Corso Garibaldi",
        "street_number" => "104",
        "zip_code" => "20121",
    ],
    [
        'user_id'=>50,
        "name" => "Viva Nachos & Burritos - Casati",
        "vat_number" => "0090449058",
        "note" => "Il ristorante accetta solo pagamenti online tramite carta di credito o PayPal",
        "thumb" => "VivaNachosCasati.webp",
        "street_name" => "Corso Garibaldi",
        "street_number" => "104",
        "zip_code" => "20121",
    ],
    [
        'user_id'=>51,
        "name" => "Ichiro",
        "vat_number" => "9468449058",
        "note" => "Il ristorante accetta solo pagamenti online tramite carta di credito o PayPal",
        "thumb" => "Ichiro.jpg",
        "street_name" => "Via San Vittore",
        "street_number" => "6",
        "zip_code" => "20123",
    ],
    [
        'user_id'=>52,
        "name" => "Pulled Lovers",
        "vat_number" => "0164449058",
        "note" => "Il ristorante accetta solo pagamenti online tramite carta di credito o PayPal",
        "thumb" => "PulledLovers.webp",
        "street_name" => "Viale Bligny",
        "street_number" => "63",
        "zip_code" => "20136",
    ],
    [
        'user_id'=>53,
        "name" => "Hattori Hanzo",
        "vat_number" => "4685449058",
        "note" => "",
        "thumb" => "HattoriHanzo.webp",
        "street_name" => "Corso Luigi Manusardi",
        "street_number" => "3",
        "zip_code" => "20136",
    ],
];
