<?php 

return [
    [
        'user_id'=>1,
        "name" => "Ristorante Primo",
        "vat_number" => "12345678910",
        "note" => "Piatti vegani e gluten free",
        "thumb" => "https://just-eat-prod-eu-res.cloudinary.com/image/upload/c_fill,f_auto,q_auto,w_1600,h_500,d_it:cuisines:italiano-4.jpg/v1/it/restaurants/227904.jpg",
        "street_name" => "Viale Giacomo Porelli",
        "street_number" => "12",
        "zip_code" => "40562",
    ],
    [
        'user_id'=>2,
        "name" => "Lago",
        "vat_number" => "24529568431",
        "note" => "Cucina italiana tradizionale di pesce",
        "thumb" => "https://just-eat-prod-eu-res.cloudinary.com/image/upload/c_fill,f_auto,q_auto,w_1600,h_500,d_it:cuisines:italiano-8.jpg/v1/it/restaurants/234708.jpg",
        "street_name" => "Viale Galli",
        "street_number" => "52",
        "zip_code" => "34522",
    ],
    [
        'user_id'=>3,
        "name" => "Memento Burger",
        "vat_number" => "01229568431",
        "note" => "Ordine minimo 15 € ",
        "thumb" => "https://just-eat-prod-eu-res.cloudinary.com/image/upload/c_fill,f_auto,q_auto,w_1600,h_500,d_it:cuisines:hamburger-8.jpg/v1/it/restaurants/268368.jpg",
        "street_name" => "Via Baldo Degli Ubaldi",
        "street_number" => "92",
        "zip_code" => "00167",
    ],
    [
        'user_id'=>4,
        "name" => "Poke House - Roma",
        "vat_number" => "00154667898",
        "note" => "La tua scelta salutare",
        "thumb" => "https://just-eat-prod-eu-res.cloudinary.com/image/upload/c_fill,f_auto,q_auto,w_1600,h_500,d_it:cuisines:poke-3.jpg/v1/it/restaurants/235613.jpg",
        "street_name" => "Via del Gambero",
        "street_number" => "36",
        "zip_code" => "00187",
    ],
    [
        'user_id'=>5,
        "name" => "Poke House - Roma",
        "vat_number" => "22559876511",
        "note" => "Consegna Gratuita",
        "thumb" => "https://just-eat-prod-eu-res.cloudinary.com/image/upload/c_fill,f_auto,q_auto,w_1600,h_500,d_it:cuisines:giapponese-6.jpg/v1/it/restaurants/202026.jpg",
        "street_name" => "Via Piacenza",
        "street_number" => "1",
        "zip_code" => "20135",
    ],
    [
        'user_id'=>6,
        "name" => "Il Principe Pizzeria Rosticceria",
        "vat_number" => "37654929299",
        "note" => "",
        "thumb" => "https://just-eat-prod-eu-res.cloudinary.com/image/upload/c_fill,f_auto,q_auto,w_1600,h_500,d_it:cuisines:giapponese-6.jpg/v1/it/restaurants/202026.jpg",
        "street_name" => "Via Piacenza",
        "street_number" => "1",
        "zip_code" => "20135",
    ],
    [
        'user_id'=>7,
        "name" => "Cipiace",
        "vat_number" => "55692987262",
        "note" => "Il ristorante accetta solo carta di credito o PayPal",
        "thumb" => "https://just-eat-prod-eu-res.cloudinary.com/image/upload/c_fill,f_auto,q_auto,w_1600,h_500,d_it:cuisines:italiano-8.jpg/v1/it/restaurants/266678.jpg",
        "street_name" => "Corso di Vittoria",
        "street_number" => "21",
        "zip_code" => "20122",
    ],
    [
        'user_id'=>8,
        "name" => "Chicken Drip",
        "vat_number" => "55692987262",
        "note" => "",
        "thumb" => "https://just-eat-prod-eu-res.cloudinary.com/image/upload/c_fill,f_auto,q_auto,w_1600,h_500,d_it:cuisines:pollo-4.jpg/v1/it/restaurants/268824.jpg",
        "street_name" => "Via California",
        "street_number" => "15",
        "zip_code" => "20144",
    ],
];